theme: jekyll-theme-cayman
title: Amazingca's Test Site
author: Amazingca
email: amazingca@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Here I will be programming a full fledged site!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
discord_username: Amazingca#3060
show_excerpts: false # set to false to remove excerpts on the homepage
